/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Array AST Node type
  * by the ASTNode.java.ftl template
  */
package org.parsers.jsonc;

import static org.parsers.jsonc.JSONCConstants.TokenType.*;
@SuppressWarnings("unused")
public class Array extends BaseNode {
}
