/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for BooleanLiteral Token subclass
  * by the ASTToken.java.ftl template
  */
package org.parsers.jsonc;

import static org.parsers.jsonc.JSONCConstants.TokenType.*;
@SuppressWarnings("unused")
public class BooleanLiteral extends Literal {
    public BooleanLiteral(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
