/* Generated by: JavaCC 21 Parser Generator. InvalidNode.java */
package org.parsers.jsonc;

/**
 * A node subtype that explicitly represents a "dirty" region of
 * an input file, that we could not parse.
 */
public class InvalidNode extends BaseNode {
    public boolean isDirty() {
        return true;
    }

}
