/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for JSONObject AST Node type
  * by the ASTNode.java.ftl template
  */
package org.parsers.json.ast;

import org.parsers.json.*;
import static org.parsers.json.JSONConstants.TokenType.*;
@SuppressWarnings("unused")
public class JSONObject extends BaseNode {
}
