/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for NullLiteral Token subclass
  * by the ASTToken.java.ftl template
  */
package org.parsers.json.ast;

import org.parsers.json.*;
import org.parsers.json.JSONConstants.TokenType;
import static org.parsers.json.JSONConstants.TokenType.*;
@SuppressWarnings("unused")
public class NullLiteral extends Literal {
    public NullLiteral(TokenType type, String image, String inputSource) {
        super(type, image, inputSource);
    }

}
